name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4

      - run: pnpm install --ignore-scripts
      - run: pnpm run build

      - run: pnpm run scripts/release.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Enable after configuring oidc
      # - run: npm publish --ignore-scripts
